/** @type {import('next').NextConfig} */

const VERSION = require("child_process")
  .execSync("git rev-parse HEAD")
  .toString()
  .trim();

const nextConfig = {
  reactStrictMode: true,
  compress: true,
  sassOptions: {
    silenceDeprecations: ['legacy-js-api', 'import', 'global-builtin', 'color-functions'],
  },
  env: {
    ALCHEMY_API_KEY: process.env.ALCHEMY_API_KEY,
    VERSION: VERSION,
    CHAIN_ID: process.env.CHAIN_ID,
    OMPUB_CONTRACT_ADDRESS: process.env.OMPUB_CONTRACT_ADDRESS,
  },
  async generateBuildId() {
    return VERSION;
  },
  i18n: {
    "locales": [
      "en",
      "ceb",
      "de",
      "sv",
      "fr",
      "nl",
      "ru",
      "es",
      "it",
      "arz",
      "pl",
      "ja",
      "zh",
      "vi",
      "war",
      "uk",
      "ar",
      "pt",
      "fa",
      "ca",
      "sr",
      "id",
      "ko",
      "no",
      "ce",
      "fi",
      "hu",
      "cs",
      "tr",
      "tt",
      "sh",
      "ro",
      "zh-min-nan",
      "eu",
      "ms",
      "eo",
      "he",
      "hy",
      "da",
      "bg",
      "cy",
      "sk",
      "azb",
      "et",
      "uz",
      "kk",
      "be",
      "simple",
      "min",
      "el",
      "hr",
      "lt",
      "gl",
      "az",
      "ur",
      "sl",
      "ka",
      "nn",
      "hi",
      "th",
      "ta",
      "la",
      "bn",
      "mk",
      "ast",
      "zh-yue",
      "lld",
      "lv",
      "tg",
      "af",
      "my",
      "mg",
      "bs",
      "mr",
      "sq",
      "oc",
      "nds",
      "ml",
      "be-tarask",
      "te",
      "ky",
      "br",
      "sw",
      "jv",
      "new",
      "vec",
      "pnb",
      "ht",
      "pms",
      "ba",
      "lb",
      "su",
      "ku",
      "ga",
      "lmo",
      "szl",
      "is",
      "fy",
      "cv",
    ],
    "defaultLocale": "en"
  }
};

module.exports = nextConfig;
